name: Version Increment

on:
  push:
    branches: ["main"]

jobs:
  increase_version:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: create tag
        id: create_tag
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

          package_version=$(node -p "require('./package.json').version")

          if [[ $package_version =~ .[0-8]. ]]; then \
            npm version minor -m "increase minor"; \
          else \
            npm version major -m "increase major"; \
          fi;

          v_version=v${package_version:0:-2}

          git tag | xargs git tag -d
          git tag $v_version
          git push origin --follow-tags
          echo "version=${v_version}" >> "$GITHUB_OUTPUT"

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          release_name: ${{ steps.create_tag.outputs.version }}
          body: Auto created by github action.
          draft: false
          prerelease: false