name: Version Increment

on:
  push:
    branches: ["test"]

jobs:
  increase_version:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create tag
        id: create_tag
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          
          version=v$(node -p "const versionSlice = require('./package.json').version.split('.'); versionSlice[0] + '.' + (+versionSlice[1] + 1)")
          npm version minor -m "$version";
          
          git tag | xargs git tag -d
          git tag -a $version -m "${{ github.ref_name }}"
          git push origin --follow-tags
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          release_name: ${{ steps.create_tag.outputs.version }}
          body: ${{ github.ref_name }}
          draft: false
          prerelease: false
