name: Increase Version
on:
  push:
    branches: ["main"]
    tags:
      - 'v*'
jobs:
  increase-version:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a ${{ github.ref }} -m "Release ${{ github.ref }}" 
          git push origin --tags
