name: Increase Version
on:
  push:
    branches: ["main"]
jobs:
  increase-version:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create tag
        id: create_tag
        run: |
          git config user.email "$GITHUB_USER_EMAIL"
          git config user.name "$GITHUB_ACTOR"
          version=v$(node -p "require('./package.json').version")
          
          npm version minor -m "v%s"

          git tag | xargs git tag -d
          git tag ${version}
          git push origin --follow-tags
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          release_name: ${{ steps.create_tag.outputs.version }}
          body: auto created
          draft: false
          prerelease: false