name: Version Increment

on:
  push:
    branches: ["test"]

jobs:
  increase_version:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create tag
        id: create_tag
        run: |
          git config user.email "$GITHUB_USER_EMAIL"
          git config user.name "$GITHUB_ACTOR"

          package_version=$(node -p "require('./package.json').version")
          new_version=v$(echo "${package_version:0:-2} + 0.1" | bc)

          if [[ $package_version =~ .[0-8]. ]]; then \
            npm version minor -m "$new_version"; \
          else \
            npm version major -m "$new_version"; \
          fi;

          git tag | xargs git tag -d
          git tag -a $new_version -m "${{ github.ref_name }}"
          git push origin --follow-tags
          echo "version=${new_version}" >> "$GITHUB_OUTPUT"

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          release_name: ${{ steps.create_tag.outputs.version }}
          body: ${{ github.ref_name }}
          draft: false
          prerelease: false